@startuml
actor "WebSocketClient" as client
actor "JuggWebSocketServer" as server
database "Custom Handlers" as customHandlers
database "EvalHandler" as evalHandler
database "EvalKiller" as evalKiller
database "Ognl Parser" as ognlParser


client -> server : connect WebSocket
client -> server : send plain text message
server -> server : wrap message as JuggCommandContext
server -> customHandlers : call customize handlers

opt
  customHandlers -> server: customize handler intercept the request and return a response
  server -> client : return
end

customHandlers -> evalHandler: call evalHandler
evalHandler -> evalKiller: call evalKiller
evalKiller -> ognlParser: call OGNL parser

ognlParser -> evalKiller: return
evalKiller -> evalHandler: return
evalHandler -> server: return
server -> client: return

@enduml
