@startuml
actor "WebSocket客户端" as client
actor "JuggWebSocket服务器" as server
database "自定义Handlers" as customHandlers
database "EvalHandler" as evalHandler
database "EvalHandler" as evalKiller
database "Ognl解析器" as ognlParser


client -> server : 请求连接 WebSocket
client -> server : 发送消息（纯文本）
server -> server : 打包消息为 JuggCommandContext
server -> customHandlers : 交给自定义 handlers 加工处理，自定义 handlers

opt
  customHandlers -> server: 自定义handler拦截请求，返回响应
  server -> client : 返回响应
end

customHandlers -> evalHandler: 把消息交给 evalHandler 处理
evalHandler -> evalKiller: 把消息交给 EvalKiller 处理
evalKiller -> ognlParser: 把命令交给 OGNL 解析器处理

ognlParser -> evalKiller: 返回执行结果
evalKiller -> evalHandler: 返回执行结果
evalHandler -> server: 返回执行结果
server -> client: 返回执行结果

@enduml